### ISSUE TITLE
Add ability to set time range for data importing

### ISSUE THREAD

**Issue by valyala** [ryotarai/prometheus-tsdb-dump#1]
### The issue

Sometimes users start replicating data to VictoriaMetrics from Prometheus, while continuing storing data to Prometheus. Then they need importing historical data from Prometheus into VictoriaMetrics, but don't won importing duplicate data, which already exists in VictoriaMetrics after it has been added as remote storage to Prometheus.

### The solution

To add ability to set time range (start and end timestamps) for data to import from Prometheus storage to VictoriaMetrics. For instance, `-startTimestamp` and `-endTimestamp` command-line flags. Default value for `-startTimestamp` should be 0, while default value for `-endTimestamp` should be `+Inf`.

**Comment by ryotarai** [comment]
Already implemented: https://github.com/ryotarai/prometheus-tsdb-dump/blob/c110d9d8c897d0efd37e719b0531a5d70e4db0c1/main.go#L26-L27
but not documented. I'm going to update README.

**Comment by ryotarai** [comment]
Updated README: https://github.com/ryotarai/prometheus-tsdb-dump/commit/2c3e0a5a14cc3f149c92cd2a70024abeb31ae2b0

**Comment by valyala** [comment]
Thanks!
